ECommerce/Components/CartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ECommerce.Data;

namespace ECommerce.Components
{
    public class CartViewComponent : ViewComponent
    {
        private readonly Cart _cart;

        public CartViewComponent(Cart cart)
        {
            _cart = cart;
        }

        public IViewComponentResult Invoke()
        {
            return View(_cart);
        }
    }
}

ECommerce/Components/LoginViewComponent.cs
using ECommerce.Areas.Identity.Pages.Account;
using ECommerce.Models.Account;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ECommerce.Components
{
    public class LoginViewComponent :ViewComponent
    {
        public LoginViewModel _model;
        public LoginViewComponent()
        {
            _model = new LoginViewModel();
        }
        public IViewComponentResult Invoke()
        {
            return View(_model);
        }
    }
}

ECommerce/Components/SearchViewComponent.cs
using ECommerce.Models.Home;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ECommerce.Components
{
    public class SearchViewComponent : ViewComponent
    {
        private SearchModel _model;
        public SearchViewComponent()
        {
            _model = new SearchModel();
        }
        public IViewComponentResult Invoke()
        {
            return View(_model);
        }
    }
}

ECommerce/Controllers/FavoriteController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ECommerce.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using ECommerce.Data;

namespace ECommerce.Controllers
{
    public class FavoriteController : Controller
    {
        private readonly IFavorite _favoriteService;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly IProduct _productService;

        public FavoriteController(IFavorite favoriteService, UserManager<IdentityUser> userManager,
            SignInManager<IdentityUser> signInManager, IProduct productService)
        {
            _favoriteService = favoriteService;
            _userManager = userManager;
            _signInManager = signInManager;
            _productService = productService;
        }

        public IActionResult Index()
        {
            if(!_signInManager.IsSignedIn(User))
            {
                return RedirectToAction("Login", "Account");
            }

            var userId = _userManager.GetUserId(User);
            var favorites = _favoriteService.GetByUserId(userId); 

            return View(favorites);
        }

        public async Task<IActionResult> AddFavorite(int id)
        {
            if (!_signInManager.IsSignedIn(User))
            {
                return RedirectToAction("Login", "Account");
            }

            var userId = _userManager.GetUserId(User);
            var model = _favoriteService.GetByUserIdAndProductId(userId, id);

            if(model !=null)
            {
                return RedirectToAction("Index");
            }

            var product = _productService.GetProductById(id);
            var favorite = new Favorite()
            {
                ProductId = product.Id,
                ProductName = product.Name,
                //ImgUrl = product.Image.Img1,
                UserId = userId
            };
            await _favoriteService.AddFavorite(favorite);

            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Delete(int id)
        {
            var favorite = _favoriteService.GetByProductId(id);
            await _favoriteService.RemoveFavorite(favorite);

            return RedirectToAction("Index");
        }

    }
}

ECommerce/Views/Shared/Success.cshtml
@model ECommerce.Models.SuccessViewModel

    <div style="text-align:center">
        <h3>Поздравляем!</h3>
        <h5>@Model.Message</h5>
    </div>

ECommerce/Views/Shared/_CatalogPartial.cshtml
<div class="mybar">
        <div class="dropCatalog" >
            <a asp-controller="Home" asp-action="TVShow" asp-route-id="tv" class="dropbtnCatalog">
                <i class="fa fa-television fa-lg" style="padding-left:5px; padding-right:5px;"></i>
                Телевизоры, аудио
            </a>
            <div class="catalog-content" >
                <div class="myrow" >
                    <div class="mycolumn">
                        <br />
                        <a asp-action="TVShow" asp-controller="Home" asp-route-id="tv0" style="text-decoration:underline;"><b>Телевизоры</b></a>
                        <a asp-action="CatDetail" asp-controller="Home" asp-route-id="1">4K Телевизоры</a>
                        <a asp-action="CatDetail" asp-controller="Home" asp-route-id="2">Смарт-телевизоры</a>
                        <a asp-action="CatDetail" asp-controller="Home" asp-route-id="3">Full HD-телевизоры</a>     
                    </div>
                    <div class="mycolumn">
                        <br />
                        <a asp-action="TVShow" asp-controller="Home" asp-route-id="tv1" style="text-decoration:underline;"><b>Цифровое ТВ</b></a>
                        <a asp-action="CatDetail" asp-controller="Home" asp-route-id="4">Триколор ТВ</a>
                        <a asp-action="CatDetail" asp-controller="Home" asp-route-id="6">НТВ-Плюс</a>
                        <a asp-action="CatDetail" asp-controller="Home" asp-route-id="5">МТС</a>
                       
                    </div>

                    <div class="mycolumn">
                        <br />
                        <a asp-action="TVShow" asp-controller="Home" asp-route-id="tv2" style="text-decoration:underline;"><b>Домашний кинотеатр</b></a>
                        <a asp-action="CatDetail" asp-controller="Home" asp-route-id="7">Домашний кинотеатр</a>
                        <a asp-action="CatDetail" asp-controller="Home" asp-route-id="8">DVD, Blu-Ray</a>
                        <a asp-action="CatDetail" asp-controller="Home" asp-route-id="9">Ресиверы</a>
                    </div>
                </div>
            </div>


        </div>
    </div>
<div class="mybar2">
    <div class="dropCatalog2">
        <a asp-controller="Home" asp-action="LapShow" class="dropbtnCatalog2" id="ctl2">
            <i class="fa fa-laptop fa-lg" style="padding-left:5px; padding-right:5px;"></i>
            Ноутбуки и компьютеры
        </a>
        <div class="catalog-content2">
            <div class="myrow2">
                <div class="mycolumn2">
                    <br />
                    <a asp-action="LapShow" asp-controller="Home" style="text-decoration:underline;">Ноутбуки</a>
                    <a href="#">Link 1</a>
                    <a href="#">Link 2</a>
                    <a href="#">Link 3</a>
                </div>
                <div class="mycolumn2">
                    <br />
                    <a asp-action="LapShow" asp-controller="Home" style="text-decoration:underline;">Компьютеры и мониторы</a>
                    <a href="#">Link 1</a>
                    <a href="#">Link 2</a>
                    <a href="#">Link 3</a>
                </div>
                <div class="mycolumn2">
                    <br />
                    <a asp-action="LapShow" asp-controller="Home" style="text-decoration:underline;">Компьютерные комплектующие</a>
                    <a href="#">Link 1</a>
                    <a href="#">Link 2</a>
                    <a href="#">Link 3</a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="cartHead">
    @await Component.InvokeAsync("Cart") 
</div>

ECommerce/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ECommerce</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom"
             id="navHeader">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ECommerce</a>
                @await Component.InvokeAsync("Search")
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">

                    @await Component.InvokeAsync("Login")
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item" style="margin:auto;">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Favorite" asp-action="Index">
                                <i class="fa fa-thumbs-o-up fa-2x" aria-hidden="true" style=""
                                   title="Избранное"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="catalogLine border-bottom">
            <div class="k_centered">
                <partial name="_CatalogPartial"/>
            </div>
        </div>
    </header>   
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ECommerce - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/login.js"></script>
    <script src="~/js/catalog.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ECommerce/Views/Shared/_SortPartial.cshtml
<h4>Partial view</h4>

<div style="display:flex;">
    <select class="custom-select mr-sm-2 edit_input" id="myselect" style="margin-bottom:10px;">
        <option value="">Сортировать по</option>
        <option  value="Home/SortAlphabet">Алфавиту</option>
        <option  value="SortRait">Популярности</option>
        <option value="SortPrice">Цене</option>
    </select>
</div>

@*<script>
    const select = document.querySelector("#myselect");
    const options = document.querySelectorAll("#myselect option");

    select.addEventListener("change", function () {
        const url = this.options[this.selectedIndex].dataset.url;
        if (url) {
            window.location.href = url;
        }
    });
</script>*@