ECommerce/Models/Home/FilterModel.cs
using System.Collections.Generic;

namespace ECommerce.Models.Home
{
    public class FilterModel
    {
        public int CategoryId { get; set; }
        public List<string> Brands { get; set; }
        public double PriceDown { get; set; }
        public double PriceUp { get; set; }
    }
}

ECommerce/Models/Home/SearchModel.cs
namespace ECommerce.Models.Home
{
    public class SearchModel
    {
        public string SearchQuery { get; set; }
    }
}

ECommerce/Models/Home/SortModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ECommerce.Models.Home
{
    public class SortModel
    {
        public int CategoryId { get; set; }
    }
}

ECommerce/Components/FilterViewComponent.cs
using ECommerce.Models.Home;
using ECommerce.Services;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace ECommerce.Components
{
    public class FilterViewComponent : ViewComponent
    {
        private readonly FilterModel _filterModel;
        private readonly IProduct _productService;

        public FilterViewComponent(IProduct productService)
        {
            _filterModel = new FilterModel();
            _productService = productService;
        }

        public IViewComponentResult Invoke(int id)
        {
            var model = _productService.GetProductByCategoryId(id);
            var modelBrands = model.Select(x => x.Brand).Distinct().ToList();
            double priceDown = model.Select(x => x.Price).Min();
            double priceUp = model.Select(x => x.Price).Max();

            _filterModel.Brands = modelBrands;
            _filterModel.PriceDown = priceDown;
            _filterModel.PriceUp = priceUp;
            _filterModel.CategoryId = id;

            return View(_filterModel);
        }
    }
}

ECommerce/Components/SortViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ECommerce.Models.Home;

namespace ECommerce.Components
{
    public class SortViewComponent : ViewComponent
    {
        private readonly SortModel _sortModel;
        public SortViewComponent()
        {
            _sortModel = new SortModel();
        }
        public IViewComponentResult Invoke(int id)
        {
            _sortModel.CategoryId = id;
            return View(_sortModel);
        }
    }
}

ECommerce/Controllers/CartController.cs
using ECommerce.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using ECommerce.Services;

namespace ECommerce.Controllers
{
    public class CartController : Controller
    {
        private readonly Cart _cart;
        private readonly IProduct _productService;

        public CartController(Cart cart, IProduct productService)
        {
            _cart = cart;
            _productService = productService;
        }

        public IActionResult AddToCart(int id)
        {
            var product = _productService.GetProductById(id);
            //product.Image = _productService.GetImageByProductId(id);
            if (product != null)
            {
                _cart.AddItem(product, 1);
            }
            return Redirect("/Blazor/CartBaseView");
        }
    }
}

ECommerce/Controllers/FavoriteController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ECommerce.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using ECommerce.Data;

namespace ECommerce.Controllers
{
    public class FavoriteController : Controller
    {
        private readonly IFavorite _favoriteService;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly IProduct _productService;

        public FavoriteController(IFavorite favoriteService, UserManager<IdentityUser> userManager,
            SignInManager<IdentityUser> signInManager, IProduct productService)
        {
            _favoriteService = favoriteService;
            _userManager = userManager;
            _signInManager = signInManager;
            _productService = productService;
        }

        public IActionResult Index()
        {
            if(!_signInManager.IsSignedIn(User))
            {
                return RedirectToAction("Login", "Account");
            }

            var userId = _userManager.GetUserId(User);
            var favorites = _favoriteService.GetByUserId(userId); 

            return View(favorites);
        }

        public async Task<IActionResult> AddFavorite(int id)
        {
            if (!_signInManager.IsSignedIn(User))
            {
                return RedirectToAction("Login", "Account");
            }

            var userId = _userManager.GetUserId(User);
            var model = _favoriteService.GetByUserIdAndProductId(userId, id);

            if(model !=null)
            {
                return RedirectToAction("Index");
            }

            var product = _productService.GetProductById(id);
            var favorite = new Favorite()
            {
                ProductId = product.Id,
                ProductName = product.Name,
                //ImgUrl = product.Image.Img1,
                UserId = userId
            };
            await _favoriteService.AddFavorite(favorite);

            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Delete(int id)
        {
            var favorite = _favoriteService.GetByProductId(id);
            await _favoriteService.RemoveFavorite(favorite);

            return RedirectToAction("Index");
        }

    }
}

ECommerce/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ECommerce.Models;
using ECommerce.Data;
using ECommerce.Services;
using ECommerce.Models.ProductModel;
using ECommerce.Models.Home;

namespace ECommerce.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ICatalog _catalogContext;
        private readonly IProduct _productService;

        public HomeController(ILogger<HomeController> logger, ICatalog catalogs, IProduct product)
        {
            _logger = logger;
            _catalogContext = catalogs;
            _productService = product;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public IActionResult TVShow(string id)
        {
            //IEnumerable<Product> _products;
            string viewName = null;

            switch (id)
            {
                case "tv":
                    var model = _catalogContext.GetSubCatalogsByCatalogId(2);
                    ViewData["Message"] = "Категории";
                    return View("TVMain", model);
                case "tv0":
                    //subid = 1
                    var model0 = _productService.GetProductsBySubCatalogId(1);

                    var prod0 = new ProductViewModel
                    {
                        Products = model0,
                        id = "tv0"
                    };

                    ViewData["Message"] = "Телевизоры";
                    return View(prod0);
                case "tv1":
                    //subid = 2
                    var model1 = _productService.GetProductsBySubCatalogId(2);
                    var prod1 = new ProductViewModel
                    {
                        Products = model1,
                        id = "tv1"
                    };
                    ViewData["Message"] = "Цифровое ТВ";
                    return View(prod1);
                case "tv2":
                    //subid = 3
                    var model2 = _productService.GetProductsBySubCatalogId(3);
                    var prod2 = new ProductViewModel
                    {
                        Products = model2,
                        id = id
                    };
                    ViewData["Message"] = "Домашний кинотеатр";
                    return View(prod2);
                default:
                    break;
            }
            return View();
        }

        public IActionResult CatDetail(int id)
        {
            var model = _productService.GetProductByCategoryId(id);

            //foreach (var item in model)
            //{
            //    item.Image = _productService.GetImageByProductId(item.Id);
            //}

            ViewData["Message"] = model.FirstOrDefault().Category;
            return View(model);
        }

        //[HttpPost]
        //public JsonResult SortAlphabet(string dataToSend)
        //{
        //    return Json(
        //        new { redirectTo = Url.Action("Index", "Home") }
        //        );
        //}
        [HttpGet]
        public IActionResult SortAlphabet(int id)
        {
            var model = _productService.GetProductByCategoryId(id).OrderBy(x => x.Name);
            ViewData["Message"] = model.FirstOrDefault().Category;
            return View("CatDetail", model);
        }

        [HttpGet]
        public IActionResult SortRait(int id)
        {
            var model = _productService.GetProductByCategoryId(id).OrderBy(x => x.Rait);
            ViewData["Message"] = model.FirstOrDefault().Category;
            return View("CatDetail", model);
        }

        [HttpGet]
        public IActionResult SortPrice(int id)
        {
            var model = _productService.GetProductByCategoryId(id).OrderBy(x => x.Price);
            ViewData["Message"] = model.FirstOrDefault().Category;
            return View("CatDetail", model);
        }

        [HttpPost]
        public IActionResult Filter(FilterModel filterModel)
        {
            string message = null;
            int cateId = filterModel.CategoryId;
            IEnumerable<Product> model = _productService.GetProductByCategoryId(cateId);
            IList<Product> viewModel = new List<Product>();

            if (filterModel.Brands != null)
            {
                foreach (var item in filterModel.Brands)
                {
                    var view = model.Where(x => x.Brand == item).FirstOrDefault();
                    viewModel.Add(view); ;
                    message += item.ToString() + " ";
                }
                model = viewModel.Where(x => x.Price >= filterModel.PriceDown && x.Price <= filterModel.PriceUp);
                ViewData["Message"] = $"{message} по цене от {filterModel.PriceDown} до {filterModel.PriceUp}";
            }
            else
            {
                model = model.Where(x => x.Price >= filterModel.PriceDown && x.Price <= filterModel.PriceUp);
                ViewData["Message"] = $"По цене от {filterModel.PriceDown} до {filterModel.PriceUp}";
            }

            return View(model);
        }
    }
}

ECommerce/Views/Home/CatDetail.cshtml
@model IEnumerable<Product>

@{ 
    int catId = 0;
    if(Model.Count()>=1)
    {
        catId = Model.FirstOrDefault().CategoryId;
    }
}

<div style="display:flex;">
    <div class="col-3">
        @await Component.InvokeAsync("Filter", new { id = catId})
    </div>
    <div class="col-8">
        <div style="display:flex;">
            <h3>@ViewData["Message"]</h3>
            <span class="headCount">@Model.Count()</span>
            <div style="display: flex; margin: 0 0 0 auto;">
                @await Component.InvokeAsync("Sort", new { id = catId })
            </div>
        </div>
        @*<table class="table table-hover">
            <tr>
                <th>Name</th>
                <th>Price</th>
                <th>Rait</th>
                <th></th>
                <th></th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Price.ToString("C2")</td>
                    <td>@item.Rait</td>
                    <td>
                        <a asp-action="AddFavorite" asp-controller="Favorite" asp-route-id="@item.Id">
                            <i class="fa fa-smile-o text-dark" aria-hidden="true" title="В избранное"></i>
                        </a>
                    </td>
                    <td>
                        <a asp-action="AddToCart" asp-controller="Cart" asp-route-id="@item.Id">
                            <i class="fa fa-cart-plus text-dark" aria-hidden="true" title="В корзину"></i>
                        </a>
                    </td>
                </tr>
            }
        </table>*@

        @foreach (var item in Model)
        {
            <div class="productContent">
                <img src="@item.Image.Img1"/>
                <div>
                    @item.Name
                </div>
                <div>
                    <i>@item.Price.ToString("C2")</i>
                    <i>@item.Rait</i>
                </div>
                <div>
                    <a asp-action="AddFavorite" asp-controller="Favorite" asp-route-id="@item.Id">
                        <i class="fa fa-smile-o text-dark" aria-hidden="true" title="В избранное"></i>
                    </a>
                    <a asp-action="AddToCart" asp-controller="Cart" asp-route-id="@item.Id">
                        <i class="fa fa-cart-plus text-dark" aria-hidden="true" title="В корзину"></i>
                    </a>
                </div>
            </div>
        }
    </div>
</div>

ECommerce/Views/Home/Filter.cshtml
@model IEnumerable<Product> 

<div class="col-8" style="margin: 0 0 0 auto;">
    <div style="display:flex;">
        <h3>@ViewData["Message"]</h3>
        <span class="headCount">@Model.Count()</span>
    </div>
    @if (Model.Count() > 0)
    {
        @foreach (var item in Model)
        {
            <div class="productContent">
                <img src="@item.Image.Img1" />
                <div>
                    @item.Name
                </div>
                <div>
                    <i>@item.Price.ToString("C2")</i>
                    <i>@item.Rait</i>
                </div>
                <div>
                    <a asp-action="AddFavorite" asp-controller="Favorite" asp-route-id="@item.Id">
                        <i class="fa fa-smile-o text-dark" aria-hidden="true" title="В избранное"></i>
                    </a>
                    <a asp-action="AddToCart" asp-controller="Cart" asp-route-id="@item.Id">
                        <i class="fa fa-cart-plus text-dark" aria-hidden="true" title="В корзину"></i>
                    </a>
                </div>
            </div>
        }
    }
</div>

ECommerce/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ECommerce/Views/Home/TVMain.cshtml
@model IEnumerable<SubCatalog>

<h3>@ViewData["Message"]</h3>
@{ 
    int i = 0;
}

<div style="width:900px; float:right; margin:50px 100px 0 0">
    @foreach (var item in Model)
    {
        
        string routeId = $"tv{i}";
        <div style="display:inline">
            <img src="@item.ImgUrl" style="height:200px;" />
            <a asp-action="TVShow" asp-controller="Home" asp-route-id="@routeId">@item.SubName</a>
        </div>
        i++;
    }
</div>

ECommerce/Views/Home/TVShow.cshtml
@*@model IEnumerable<Product>*@
@model ECommerce.Models.ProductModel.ProductViewModel


<div style="display:flex;">
    <div class="col-2">@await Component.InvokeAsync("Category", new { id = Model.id})</div>
    <div class="col-10">
        <h3>@ViewData["Message"]</h3>
        @foreach (var item in Model.Products)
        {
            <div style="height:150px;">
                Имя @item.Name   категория @item.Category
                <div style="display:flex;">
                    <div style="margin:10px;">
                        <a asp-action="AddFavorite" asp-controller="Favorite" asp-route-id="@item.Id">
                            <i class="fa fa-smile-o text-dark" aria-hidden="true" title="В избранное"></i>
                        </a>
                    </div>
                    <div style="margin:10px;">
                        <a asp-action="AddToCart" asp-controller="Cart" asp-route-id="@item.Id">
                            <i class="fa fa-cart-plus text-dark" aria-hidden="true" title="В корзину"></i>
                        </a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>